Repository PLANBTI/PLANBTI, pull requests merged in 2023-06, with the labels that each got.

#49 design : 기본 레이아웃 수정
  src/main/resources/templates/address/create.html
  src/main/resources/templates/address/modify.html
  src/main/resources/templates/adm/admLayout.html
  src/main/resources/templates/adm/faqList.html
  src/main/resources/templates/adm/main.html
  src/main/resources/templates/adm/members.html
  src/main/resources/templates/adm/reviews.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/faq/create.html
  src/main/resources/templates/faq/faq.html
  src/main/resources/templates/faq/modify.html
  src/main/resources/templates/member/faqList.html
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/orderlist.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/shoppingbasket.html
  src/main/resources/templates/member/testResult.html
Labels: enhancement

#65 fix: 장바구니 기능 로직 오류 수정
  src/main/java/com/example/demo/boundedContext/product/entity/Basket.java
  src/main/java/com/example/demo/boundedContext/product/service/ShoppingBasketService.java
Labels: fix

#69 fix: 객체 저장 후 이벤트 발생하도록 수정
  src/main/java/com/example/demo/boundedContext/faq/Service/CommentService.java
  src/main/java/com/example/demo/boundedContext/member/service/AddressService.java
Labels: fix

#74 refactor: 모니터링 툴 log 삭제
  src/main/java/com/example/demo/base/security/filter/PrometheusAuthenticationFilter.java
Labels: refactoring

#72 refactor: 코드리뷰 리펙토링 및 prod.yml 수정
  src/main/java/com/example/demo/base/AppEnv.java
  src/main/java/com/example/demo/boundedContext/member/entity/MbtiTest.java
  src/main/java/com/example/demo/boundedContext/member/service/TestService.java
  src/main/resources/application-prod.yml
  src/main/resources/templates/member/mbtiTest.html
Labels: refactoring

#81 refactor : 상품 관리자 기능
  src/main/java/com/example/demo/base/adm/controller/AdmController.java
  src/main/java/com/example/demo/base/initdata/CustomInitData.java
  src/main/java/com/example/demo/boundedContext/product/service/ProductService.java
  src/main/resources/templates/adm/productModify.html
Labels: refactoring, fix

#92 fix : 삭제 후 목록 조회 되는 오류 수정
  src/main/java/com/example/demo/base/shop/ShopController.java
  src/main/java/com/example/demo/base/shop/ShopService.java
  src/main/java/com/example/demo/boundedContext/product/repository/product/ProductQueryDslRepositoryImpl.java
  src/main/java/com/example/demo/boundedContext/product/repository/product/ProductRepository.java
  src/main/java/com/example/demo/boundedContext/product/service/ProductService.java
Labels: bug, fix
